---
kind: pkgfile.Build
spec:
  targets:
    # - non-related to the kernel, in alphabetical order
    - apparmor
    - base
    - ca-certificates
    - cni
    - containerd
    - cryptsetup
    - dosfstools
    - e2fsprogs
    - fhs
    - flannel-cni
    - grub
    - ipmitool
    - iptables
    - ipxe
    - kmod
    - libaio
    - libattr
    - libcap
    - libinih
    - libjson-c
    - liblzma
    - libmnl
    - libnftnl
    - libpopt
    - libseccomp
    - libselinux
    - libsepol
    - liburcu
    - linux-firmware
    - lvm2
    - musl
    - openssl
    - pcre2
    - runc
    - sd-boot
    - socat
    - systemd-udevd
    - util-linux
    - xfsprogs
    # - kernel & dependent packages (out of tree kernel modules)
    #   kernel first, then packages in alphabetical order
    - kernel
    - drbd-pkg
    - gasket-driver-pkg
    - nvidia-open-gpu-kernel-modules-lts-pkg
    - nvidia-open-gpu-kernel-modules-production-pkg
    - zfs-pkg
  additionalTargets:
    nonfree:
      - nonfree-kmod-nvidia-lts-pkg
      - nonfree-kmod-nvidia-production-pkg
  reproducibleTargetName: reproducibility
---
kind: auto.CustomSteps
spec:
  steps:
    - name: kernel-olddefconfig
      toplevel: true
    - name: kernel-%
      toplevel: true
---
kind: custom.Step
name: kernel-olddefconfig
spec:
  makefile:
    enabled: true
    script:
      - |
        @$(MAKE) local-kernel-build TARGET_ARGS="--build-arg=KERNEL_TARGET=olddefconfig" PLATFORM=linux/amd64 DEST="kernel/build"
        @$(MAKE) local-kernel-build TARGET_ARGS="--build-arg=KERNEL_TARGET=olddefconfig" PLATFORM=linux/arm64 DEST="kernel/build"
---
kind: custom.Step
name: kernel-%
spec:
  makefile:
    enabled: true
    script:
      - |
        for platform in $(shell echo $(PLATFORM) | tr "," " "); do \
          arch=`basename $$platform` ; \
          $(MAKE) docker-kernel-prepare PLATFORM=$$platform BUILDKIT_MULTI_PLATFORM=0 TARGET_ARGS="--tag=$(REGISTRY)/$(USERNAME)/kernel:$(TAG)-$$arch --load"; \
          docker run --rm -it --entrypoint=/bin/bash -w /src -v $$PWD/kernel/build/config-$$arch:/host/.hostconfig $(REGISTRY)/$(USERNAME)/kernel:$(TAG)-$$arch -c 'cp /host/.hostconfig .config && make $* && cp .config /host/.hostconfig'; \
        done
---
kind: common.Renovate
spec:
  packageRules:
    - matchPackageNames:
        - git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
      allowedVersions: "<= 6.12"
    - matchPackageNames:
        - ipmitool/ipmitool
        - git://sourceware.org/git/lvm2.git
      versioning: 'regex:^(?<major>\d+)_(?<minor>\d+)_?(?<patch>\d+)?$'
    - matchPackageNames:
        - git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
      versioning: 'regex:^(?<major>\d{4})(?<minor>\d{2})(?<patch>\d{2})\.?(?<build>\d+)?$'
    - matchPackageNames:
        - git://git.kernel.org/pub/scm/boot/syslinux/syslinux.git
        - git://git.kernel.org/pub/scm/utils/util-linux/util-linux.git
        - nvidia/open-gpu-kernel-modules
        - dosfstools/dosfstools
        - git://git.savannah.gnu.org/grub.git
        - https://pagure.io/libaio.git
        - rpm-software-management/popt
        - PCRE2Project/pcre2
        - SELinuxProject/selinux
        - git://git.liburcu.org/userspace-rcu.git
        - git://git.kernel.org/pub/scm/libs/libcap/libcap.git
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d+)\.?(?<patch>\d+)?$'
    - matchPackageNames:
        - git://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git
        - benhoyt/inih
        - systemd/systemd
      versioning: 'regex:^(?<major>\d+)\.?(?<minor>\d+)?\.?(?<patch>\d+)?$'
    - matchPackageNames:
        - git://repo.or.cz/socat.git
        - json-c/json-c
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d+)\.?(?<patch>\d+)?\.?(?<build>\d+)?$'
    - matchPackageNames:
        - openzfs/zfs
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d+)\.?(?<patch>[0-9]{1}[0-8]{0,1})?$'
